package assignment;

import javax.swing.*;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raymo
 */
public class BoggleGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    private Game game;
    private JButton[][] gameBoard;


    public BoggleGUI() {
        game = new Game();
        gameBoard = new JButton[game.getBoard().length][game.getBoard().length];
        initComponents();
        populateDiceArray();
        setButtonText();
        ArrayList<JButton> high = new ArrayList<>();
        high.add(gameBoard[3][2]);
        highlightButtons(high);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        R1C1 = new javax.swing.JButton();
        R1C2 = new javax.swing.JButton();
        R1C3 = new javax.swing.JButton();
        R1C4 = new javax.swing.JButton();
        R2C1 = new javax.swing.JButton();
        R2C4 = new javax.swing.JButton();
        R2C3 = new javax.swing.JButton();
        R2C2 = new javax.swing.JButton();
        R3C1 = new javax.swing.JButton();
        R3C2 = new javax.swing.JButton();
        R3C3 = new javax.swing.JButton();
        R3C4 = new javax.swing.JButton();
        R4C1 = new javax.swing.JButton();
        R4C2 = new javax.swing.JButton();
        R4C3 = new javax.swing.JButton();
        R4C4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));
        setMaximumSize(new java.awt.Dimension(365, 459));
        setMinimumSize(new java.awt.Dimension(365, 459));
        setResizable(false);

        R1C1.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R1C1.setMaximumSize(new java.awt.Dimension(80, 80));
        R1C1.setMinimumSize(new java.awt.Dimension(80, 80));
        R1C1.setPreferredSize(new java.awt.Dimension(80, 80));

        R1C2.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R1C2.setText("A");
        R1C2.setMaximumSize(new java.awt.Dimension(80, 80));
        R1C2.setMinimumSize(new java.awt.Dimension(80, 80));
        R1C2.setPreferredSize(new java.awt.Dimension(80, 80));

        R1C3.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R1C3.setText("A");
        R1C3.setMaximumSize(new java.awt.Dimension(80, 80));
        R1C3.setMinimumSize(new java.awt.Dimension(80, 80));
        R1C3.setPreferredSize(new java.awt.Dimension(80, 80));

        R1C4.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R1C4.setMaximumSize(new java.awt.Dimension(80, 80));
        R1C4.setMinimumSize(new java.awt.Dimension(80, 80));
        R1C4.setPreferredSize(new java.awt.Dimension(80, 80));

        R2C1.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R2C1.setMaximumSize(new java.awt.Dimension(80, 80));
        R2C1.setMinimumSize(new java.awt.Dimension(80, 80));
        R2C1.setPreferredSize(new java.awt.Dimension(80, 80));

        R2C4.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R2C4.setMaximumSize(new java.awt.Dimension(80, 80));
        R2C4.setMinimumSize(new java.awt.Dimension(80, 80));
        R2C4.setPreferredSize(new java.awt.Dimension(80, 80));

        R2C3.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R2C3.setText("A");
        R2C3.setMaximumSize(new java.awt.Dimension(80, 80));
        R2C3.setMinimumSize(new java.awt.Dimension(80, 80));
        R2C3.setPreferredSize(new java.awt.Dimension(80, 80));

        R2C2.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R2C2.setText("A");
        R2C2.setMaximumSize(new java.awt.Dimension(80, 80));
        R2C2.setMinimumSize(new java.awt.Dimension(80, 80));
        R2C2.setPreferredSize(new java.awt.Dimension(80, 80));

        R3C1.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R3C1.setMaximumSize(new java.awt.Dimension(80, 80));
        R3C1.setMinimumSize(new java.awt.Dimension(80, 80));
        R3C1.setPreferredSize(new java.awt.Dimension(80, 80));

        R3C2.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R3C2.setMaximumSize(new java.awt.Dimension(80, 80));
        R3C2.setMinimumSize(new java.awt.Dimension(80, 80));
        R3C2.setPreferredSize(new java.awt.Dimension(80, 80));

        R3C3.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R3C3.setText("A");
        R3C3.setMaximumSize(new java.awt.Dimension(80, 80));
        R3C3.setMinimumSize(new java.awt.Dimension(80, 80));
        R3C3.setPreferredSize(new java.awt.Dimension(80, 80));

        R3C4.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R3C4.setText("A");
        R3C4.setMaximumSize(new java.awt.Dimension(80, 80));
        R3C4.setMinimumSize(new java.awt.Dimension(80, 80));
        R3C4.setPreferredSize(new java.awt.Dimension(80, 80));

        R4C1.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R4C1.setMaximumSize(new java.awt.Dimension(80, 80));
        R4C1.setMinimumSize(new java.awt.Dimension(80, 80));
        R4C1.setPreferredSize(new java.awt.Dimension(80, 80));

        R4C2.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R4C2.setMaximumSize(new java.awt.Dimension(80, 80));
        R4C2.setMinimumSize(new java.awt.Dimension(80, 80));
        R4C2.setPreferredSize(new java.awt.Dimension(80, 80));

        R4C3.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R4C3.setText("A");
        R4C3.setMaximumSize(new java.awt.Dimension(80, 80));
        R4C3.setMinimumSize(new java.awt.Dimension(80, 80));
        R4C3.setPreferredSize(new java.awt.Dimension(80, 80));

        R4C4.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        R4C4.setText("A");
        R4C4.setMaximumSize(new java.awt.Dimension(80, 80));
        R4C4.setMinimumSize(new java.awt.Dimension(80, 80));
        R4C4.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R1C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R1C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R2C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R2C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(R3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R3C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R3C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(R4C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R4C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R4C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R4C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(R1C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R1C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(R2C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R2C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(R3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(R3C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(R3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R3C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(R4C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(R4C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(R4C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R4C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoggleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoggleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoggleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoggleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoggleGUI().setVisible(true);
            }
        });
    }

    private void populateDiceArray(){
        gameBoard[0][0] = R1C1;
        gameBoard[0][1] = R1C2;
        gameBoard[0][2] = R1C3;
        gameBoard[0][3] = R1C4;
        gameBoard[1][0] = R2C1;
        gameBoard[1][3] = R2C4;
        gameBoard[1][2] = R2C3;
        gameBoard[1][1] = R2C2;
        gameBoard[2][0] = R3C1;
        gameBoard[2][1] = R3C2;
        gameBoard[2][2] = R3C3;
        gameBoard[2][3] = R3C4;
        gameBoard[3][0] = R4C1;
        gameBoard[3][1] = R4C2;
        gameBoard[3][2] = R4C3;
        gameBoard[3][3] = R4C4;
    }

    private void setButtonText() {
        for (int r = 0; r < gameBoard.length; r++) {
            for (int c = 0; c < gameBoard[r].length; c++) {
                gameBoard[r][c].setText(game.getBoard()[r][c] + "");
            }
        }
    }

    private void highlightButtons(ArrayList<JButton> buttonsToHighlight){
        for (int i = 0; i < gameBoard.length; i++){
            for (int j = 0; j < gameBoard[0].length; j++){
                gameBoard[i][j].setBackground(new java.awt.Color(240,240,240));
            }
        }
        for (JButton highlight : buttonsToHighlight){
            highlight.setBackground(new java.awt.Color(0, 255, 204));
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton R2C1;
    private javax.swing.JButton R2C4;
    private javax.swing.JButton R1C1;
    private javax.swing.JButton R2C3;
    private javax.swing.JButton R2C2;
    private javax.swing.JButton R3C1;
    private javax.swing.JButton R3C2;
    private javax.swing.JButton R3C3;
    private javax.swing.JButton R3C4;
    private javax.swing.JButton R4C1;
    private javax.swing.JButton R4C2;
    private javax.swing.JButton R4C3;
    private javax.swing.JButton R4C4;
    private javax.swing.JButton R1C2;
    private javax.swing.JButton R1C3;
    private javax.swing.JButton R1C4;
    // End of variables declaration
}
